version: '3.7'
services:
  coturn:
    image: '127.0.0.1:5000/coturn-master'
    environment:
      - TURN_PORT=3478
      - TURN_PORT_START=10000
      - TURN_PORT_END=20000
      - TURN_SECRET=mysecret
      - TURN_SERVER_NAME=coturn
      - TURN_REALM=teams.cyber.lk
      - ALTERNATE_SERVER1=62.210.172.198
      - ALTERNATE_SERVER3=62.210.140.169
      - ALTERNATE_SERVER1=62.210.127.176
    deploy:
      placement:
        constraints:
          - node.hostname == node4          
    networks:
      - host
  coturn1:
    image: '127.0.0.1:5000/coturn-slave'
    environment:
      - TURN_PORT=3478
      - TURN_PORT_START=10000
      - TURN_PORT_END=20000
      - TURN_SECRET=mysecret
      - TURN_SERVER_NAME=coturn1
      - TURN_REALM=teams.cyber.lk
    deploy:
      placement:
        constraints:
          - node.hostname == node1          
    networks:
      - host
  coturn2:
    image: '127.0.0.1:5000/coturn-slave'
    environment:
      - TURN_PORT=3478
      - TURN_PORT_START=10000
      - TURN_PORT_END=20000
      - TURN_SECRET=mysecret
      - TURN_SERVER_NAME=coturn2
      - TURN_REALM=teams.cyber.lk
    deploy:
      placement:
        constraints:
          - node.hostname == node2          
    networks:
      - host
  coturn3:
    image: '127.0.0.1:5000/coturn-slave'
    environment:
      - TURN_PORT=3478
      - TURN_PORT_START=10000
      - TURN_PORT_END=20000
      - TURN_SECRET=mysecret
      - TURN_SERVER_NAME=coturn3
      - TURN_REALM=teams.cyber.lk
    deploy:
      placement:
        constraints:
          - node.hostname == node3          
    networks:
      - host 
  
networks:
  host:
    external: true
   

